version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    env_file: .env
    image: postgres:13
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: yenofven/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
  frontend:
    env_file: .env
    image: yenofven/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: yenofven/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_volume:/staticfiles
      - media_volume:/app/media
